export const SPORT_ATTRIBUTE_WEIGHTS = {
  handEyeCoordination: { label: "hand-eye coordination", weight: 1.2 },
  footEyeCoordination: { label: "foot-eye coordination", weight: 1.1 },
  explosiveMovement: { label: "explosive movement", weight: 1 },
  runningDemand: { label: "running demand", weight: 0.95 },
  agility: { label: "agility", weight: 1 },
  endurance: { label: "endurance", weight: 0.85 },
  rotationalMovement: { label: "rotational movement", weight: 0.85 },
  teamPlay: { label: "team play", weight: 0.8 },
  spatialAwareness: { label: "spatial awareness", weight: 0.8 },
  equipmentSkill: { label: "equipment-specific skill", weight: 0.75 },
  verticalJump: { label: "vertical power", weight: 0.65 },
  contactTolerance: { label: "contact tolerance", weight: 0.55 },
};

export const SPORT_TAXONOMY = [
  {
    sport: "Cricket",
    attributes: {
      handEyeCoordination: 0.95,
      explosiveMovement: 0.72,
      runningDemand: 0.58,
      agility: 0.62,
      endurance: 0.5,
      rotationalMovement: 0.9,
      teamPlay: 0.78,
      spatialAwareness: 0.72,
      equipmentSkill: 0.95,
    },
    profileTags: ["team", "bat-and-ball", "outdoor"],
  },
  {
    sport: "Football",
    attributes: {
      footEyeCoordination: 0.95,
      explosiveMovement: 0.86,
      runningDemand: 0.9,
      agility: 0.9,
      endurance: 0.82,
      teamPlay: 0.92,
      spatialAwareness: 0.9,
      contactTolerance: 0.62,
    },
    profileTags: ["team", "outdoor", "high-running"],
  },
  {
    sport: "Field hockey",
    attributes: {
      handEyeCoordination: 0.86,
      footEyeCoordination: 0.7,
      explosiveMovement: 0.8,
      runningDemand: 0.86,
      agility: 0.88,
      endurance: 0.78,
      rotationalMovement: 0.62,
      teamPlay: 0.9,
      spatialAwareness: 0.86,
      equipmentSkill: 0.9,
    },
    profileTags: ["team", "stick-and-ball", "outdoor", "high-running"],
  },
  {
    sport: "Badminton",
    attributes: {
      handEyeCoordination: 0.9,
      explosiveMovement: 0.9,
      runningDemand: 0.45,
      agility: 0.95,
      endurance: 0.68,
      rotationalMovement: 0.64,
      spatialAwareness: 0.78,
      equipmentSkill: 0.78,
      verticalJump: 0.58,
    },
    profileTags: ["racket", "indoor", "individual-or-doubles"],
  },
  {
    sport: "Tennis",
    attributes: {
      handEyeCoordination: 0.92,
      explosiveMovement: 0.82,
      runningDemand: 0.68,
      agility: 0.86,
      endurance: 0.76,
      rotationalMovement: 0.82,
      spatialAwareness: 0.76,
      equipmentSkill: 0.86,
    },
    profileTags: ["racket", "individual-or-doubles", "outdoor"],
  },
  {
    sport: "Basketball",
    attributes: {
      handEyeCoordination: 0.76,
      explosiveMovement: 0.9,
      runningDemand: 0.82,
      agility: 0.88,
      endurance: 0.76,
      teamPlay: 0.9,
      spatialAwareness: 0.9,
      verticalJump: 0.9,
      contactTolerance: 0.58,
    },
    profileTags: ["team", "indoor", "high-running"],
  },
  {
    sport: "Volleyball",
    attributes: {
      handEyeCoordination: 0.82,
      explosiveMovement: 0.84,
      runningDemand: 0.42,
      agility: 0.76,
      endurance: 0.58,
      teamPlay: 0.9,
      spatialAwareness: 0.82,
      verticalJump: 0.92,
    },
    profileTags: ["team", "indoor", "court"],
  },
  {
    sport: "Table tennis",
    attributes: {
      handEyeCoordination: 0.96,
      explosiveMovement: 0.62,
      runningDemand: 0.22,
      agility: 0.82,
      endurance: 0.48,
      rotationalMovement: 0.64,
      spatialAwareness: 0.68,
      equipmentSkill: 0.82,
    },
    profileTags: ["racket", "indoor", "individual-or-doubles"],
  },
  {
    sport: "Kabaddi",
    attributes: {
      explosiveMovement: 0.92,
      runningDemand: 0.62,
      agility: 0.9,
      endurance: 0.74,
      teamPlay: 0.84,
      spatialAwareness: 0.8,
      contactTolerance: 0.95,
    },
    profileTags: ["team", "contact", "indoor-or-outdoor"],
  },
  {
    sport: "Athletics sprint",
    attributes: {
      explosiveMovement: 0.98,
      runningDemand: 0.82,
      agility: 0.52,
      endurance: 0.56,
    },
    profileTags: ["individual", "outdoor", "running"],
  },
];
